version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - odoo_network

  odoo:
    image: odoo:16.0
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DB=odoo
    ports:
      - "8069:8069"
    volumes:
      - ./data/odoo:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    depends_on:
      - db
    networks:
      - odoo_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"  # Port 5050 pour accéder à pgAdmin dans le navigateur
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Volume pour stocker les données de pgAdmin
    networks:
      - odoo_network

networks:
  odoo_network:
    driver: bridge

volumes:
  pgadmin_data:
    driver: local
