---
---
# 1. Créer le répertoire de travail pour Odoo
- name: Créer le répertoire de travail pour Odoo
  file:
    path: /opt/odoo
    state: directory
    owner: root
    group: root
    mode: '0755'

# 2. Copier le fichier Docker Compose pour Odoo
- name: Copier le fichier docker-compose pour Odoo
  template:
    src: docker-compose-odoo.yml.j2
    dest: /opt/odoo/docker-compose.yml

# 3. Créer le répertoire pour les volumes persistants
- name: Créer le répertoire pour les volumes persistants
  file:
    path: "{{ odoo_volume_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

# 4. Lancer le service Odoo avec Docker Compose
- name: Lancer le service Odoo avec Docker Compose
  command: docker-compose up -d
  args:
    chdir: /opt/odoo
