version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: "{{ pgadmin_container_name }}"
    ports:
      - "{{ pgadmin_port }}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "{{ pgadmin_email }}"
      PGADMIN_DEFAULT_PASSWORD: "{{ pgadmin_password }}"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
